import '../../bible_block_catalog.dart';
import '../bible_block_contract.dart';
import '../layout/page_layout_recipe_registry.dart';
import '../model/bible_block.dart';
import '../model/bible_block_layout.dart';
import '../model/bible_document.dart';
import '../model/bible_page.dart';
import '../model/bible_page_mode.dart';
import '../theme/bible_theme.dart';
import 'bible_template_package.dart';

/// Plantilla V2 estándar: 4 grupos y 13 apartados de la Biblia legacy.
abstract final class BibleIrisStandardTemplate {
  static const id = 'v2_iris_standard';

  static BibleTemplatePackage get package {
    final theme = BibleThemePresets.irisStandard;
    const groups = [
      BibleDocumentGroup(id: 'narrative', label: 'Narrativa y creativa'),
      BibleDocumentGroup(
        id: 'technical',
        label: 'Técnica de imagen',
        sortOrder: 1,
      ),
      BibleDocumentGroup(
        id: 'spatial',
        label: 'Espacial y pruebas',
        sortOrder: 2,
      ),
      BibleDocumentGroup(
        id: 'operational',
        label: 'Operativa y referencias',
        sortOrder: 3,
      ),
    ];
    final pages = <BiblePage>[
      _page(
        id: 'direction',
        groupId: 'narrative',
        label: 'Dirección',
        sortOrder: 0,
        recipe: PageLayoutRecipeRegistry.directionBento,
        blocks: [
          _b(
            'direction__header',
            BibleBlockKind.chipSelect,
            'headerTags',
            'header',
            'Cabecera de escena',
            colSpan: 6,
          ),
          _b(
            'direction__narrative',
            BibleBlockKind.narrative,
            'narrativeIntent',
            'narrative',
            'Intención narrativa',
            colSpan: 8,
            rowSpan: 3,
          ),
          _b(
            'direction__tone',
            BibleBlockKind.text,
            'tonePoints',
            'toneStrategies',
            'Tono y atmósfera',
            colSpan: 4,
            rowSpan: 3,
          ),
          _b(
            'direction__strategy',
            BibleBlockKind.text,
            'visualStrategy',
            'visualStrategy',
            'Estrategia visual',
          ),
          _b(
            'direction__acts',
            BibleBlockKind.dynamicBlocks,
            'acts',
            'acts',
            'Intención visual por acto',
          ),
          _b(
            'direction__trans',
            BibleBlockKind.text,
            'transitions',
            'transitions',
            'Lenguaje de transiciones',
          ),
          _b(
            'direction__refs',
            BibleBlockKind.moodboardRefs,
            'narrativeRefs',
            'references',
            'Referencias de dirección',
            rowSpan: 3,
          ),
        ],
      ),
      _page(
        id: 'concept',
        groupId: 'narrative',
        label: 'Concepto de imagen',
        sortOrder: 1,
        recipe: PageLayoutRecipeRegistry.conceptBento,
        blocks: [
          _b(
            'concept__narrative',
            BibleBlockKind.narrative,
            'narrativeIntent',
            'narrative',
            'Intención narrativa',
            rowSpan: 3,
          ),
          _b(
            'concept__palette',
            BibleBlockKind.colorPalette,
            'paletteTarget',
            'colorPalette',
            'Paleta de color',
          ),
          _b(
            'concept__symbol',
            BibleBlockKind.text,
            'textField',
            'colorSymbolism',
            'Simbología de color',
            colSpan: 6,
          ),
          _b(
            'concept__light',
            BibleBlockKind.text,
            'textField',
            'lightPhilosophy',
            'Filosofía de luz',
            colSpan: 6,
          ),
          _b(
            'concept__key',
            BibleBlockKind.heroImage,
            'heroWithCaption',
            'keyFrame',
            'Key Frame Analysis',
            rowSpan: 3,
          ),
          _b(
            'concept__shadow',
            BibleBlockKind.text,
            'textField',
            'shadowTreatment',
            'Tratamiento de sombras',
            colSpan: 6,
          ),
          _b(
            'concept__acts',
            BibleBlockKind.text,
            'textField',
            'actComposition',
            'Composición por actos',
            colSpan: 6,
          ),
          _b(
            'concept__notes',
            BibleBlockKind.text,
            'textField',
            'actNotes',
            'Intención visual por acto',
            colSpan: 6,
          ),
          _b(
            'concept__refs',
            BibleBlockKind.moodboardRefs,
            'moodboardRefs',
            'references',
            'Referencias visuales',
            rowSpan: 3,
          ),
        ],
      ),
      _page(
        id: 'camera',
        groupId: 'technical',
        label: 'Cámara y sensor',
        sortOrder: 0,
        recipe: PageLayoutRecipeRegistry.cameraSpecsHud,
        blocks: [
          _b(
            'camera__narrative',
            BibleBlockKind.narrative,
            'narrativeIntent',
            'narrative',
            'Intención narrativa',
            rowSpan: 3,
          ),
          _b(
            'camera__body',
            BibleBlockKind.text,
            'textField',
            'cameraBody',
            'Cámara y formato',
            colSpan: 6,
          ),
          _b(
            'camera__philo',
            BibleBlockKind.text,
            'textField',
            'philosophy',
            'Filosofía de cámara',
            colSpan: 6,
          ),
          _b(
            'camera__move',
            BibleBlockKind.text,
            'textField',
            'movements',
            'Movimientos de cámara',
            colSpan: 6,
          ),
          _b(
            'camera__specs',
            BibleBlockKind.text,
            'textField',
            'specsReference',
            'Fichas técnicas',
            colSpan: 6,
          ),
          _b(
            'camera__refs',
            BibleBlockKind.moodboardRefs,
            'moodboardRefs',
            'references',
            'Referencias visuales',
            rowSpan: 3,
          ),
        ],
      ),
      _page(
        id: 'optics',
        groupId: 'technical',
        label: 'Óptica',
        sortOrder: 1,
        recipe: PageLayoutRecipeRegistry.opticsSpecs,
        blocks: [
          _b(
            'optics__narrative',
            BibleBlockKind.narrative,
            'narrativeIntent',
            'narrative',
            'Intención narrativa',
            rowSpan: 3,
          ),
          _b(
            'optics__kit',
            BibleBlockKind.text,
            'textField',
            'opticSettings',
            'Filosofía y kit de lentes',
            colSpan: 6,
          ),
          _b(
            'optics__refs',
            BibleBlockKind.moodboardRefs,
            'moodboardRefs',
            'references',
            'Referencias visuales',
            rowSpan: 3,
          ),
        ],
      ),
      _page(
        id: 'exposure',
        groupId: 'technical',
        label: 'Exposición',
        sortOrder: 2,
        recipe: PageLayoutRecipeRegistry.exposureHud,
        blocks: [
          _b(
            'exposure__narrative',
            BibleBlockKind.narrative,
            'narrativeIntent',
            'narrative',
            'Intención narrativa',
            rowSpan: 3,
          ),
          _b(
            'exposure__global',
            BibleBlockKind.telemetry,
            'telemetryPanel',
            'globalExposure',
            'Exposición global',
            colSpan: 6,
          ),
          _b(
            'exposure__blocks',
            BibleBlockKind.dynamicBlocks,
            'dynamicBlocks',
            'blocks',
            'Bloques de exposición',
          ),
          _b(
            'exposure__refs',
            BibleBlockKind.moodboardRefs,
            'moodboardRefs',
            'references',
            'Referencias visuales',
            rowSpan: 3,
          ),
        ],
      ),
      _page(
        id: 'lighting',
        groupId: 'technical',
        label: 'Iluminación',
        sortOrder: 3,
        recipe: PageLayoutRecipeRegistry.lightingAnalysis,
        blocks: [
          _b(
            'lighting__overview',
            BibleBlockKind.narrative,
            'narrativeIntent',
            'overview',
            'Visión general',
            rowSpan: 3,
          ),
          _b(
            'lighting__metrics',
            BibleBlockKind.telemetry,
            'telemetryPanel',
            'globalMetrics',
            'Sensación de temperatura',
            colSpan: 6,
          ),
          _b(
            'lighting__mosaic',
            BibleBlockKind.heroImage,
            'behaviorMosaic',
            'lightBehaviors',
            'Comportamiento de la luz',
          ),
          _b(
            'lighting__film',
            BibleBlockKind.narrative,
            'cardDeck',
            'filmRefs',
            'Referencias fílmicas',
          ),
          _b(
            'lighting__locs',
            BibleBlockKind.dynamicBlocks,
            'cardDeck',
            'locationLights',
            'Localizaciones (luz)',
          ),
        ],
      ),
      _page(
        id: 'color_image',
        groupId: 'technical',
        label: 'Color e imagen',
        sortOrder: 4,
        recipe: PageLayoutRecipeRegistry.colorImage,
        blocks: [
          _b(
            'color__narrative',
            BibleBlockKind.narrative,
            'narrativeIntent',
            'narrative',
            'Intención narrativa',
            rowSpan: 3,
          ),
          _b(
            'color__lut',
            BibleBlockKind.text,
            'textField',
            'lut',
            'LUT y color science',
            colSpan: 6,
          ),
          _b(
            'color__palettes',
            BibleBlockKind.colorPalette,
            'paletteTarget',
            'blocks',
            'Paletas por bloque',
          ),
          _b(
            'color__temp',
            BibleBlockKind.telemetry,
            'telemetryPanel',
            'baseTemp',
            'Temperatura base (K)',
            colSpan: 6,
          ),
          _b(
            'color__refs',
            BibleBlockKind.moodboardRefs,
            'moodboardRefs',
            'references',
            'Referencias visuales',
            rowSpan: 3,
          ),
        ],
      ),
      _page(
        id: 'format',
        groupId: 'technical',
        label: 'Aspect ratio',
        sortOrder: 5,
        recipe: PageLayoutRecipeRegistry.aspectRatioHud,
        blocks: [
          _b(
            'format__header',
            BibleBlockKind.chipSelect,
            'headerTags',
            'header',
            'Cabecera',
            colSpan: 6,
          ),
          _b(
            'format__narrative',
            BibleBlockKind.narrative,
            'narrativeIntent',
            'narrative',
            'Intención narrativa',
            rowSpan: 3,
          ),
          _b(
            'format__settings',
            BibleBlockKind.text,
            'textField',
            'formatSettings',
            'Aspect ratio y entrega',
            colSpan: 6,
          ),
          _b(
            'format__refs',
            BibleBlockKind.moodboardRefs,
            'moodboardRefs',
            'references',
            'Referencias visuales',
            rowSpan: 3,
          ),
        ],
      ),
      _page(
        id: 'texture',
        groupId: 'technical',
        label: 'Textura',
        sortOrder: 6,
        recipe: PageLayoutRecipeRegistry.textureLook,
        blocks: [
          _b(
            'texture__narrative',
            BibleBlockKind.narrative,
            'narrativeIntent',
            'narrative',
            'Intención narrativa',
            rowSpan: 3,
          ),
          _b(
            'texture__macro',
            BibleBlockKind.heroImage,
            'heroWithCaption',
            'macroPreview',
            'Vista macro grano / ruido',
            rowSpan: 3,
          ),
          _b(
            'texture__grain',
            BibleBlockKind.text,
            'textField',
            'filmGrain',
            'Film Grain',
            colSpan: 6,
          ),
          _b(
            'texture__diff',
            BibleBlockKind.text,
            'textField',
            'diffusion',
            'Diffusion Optics',
            colSpan: 6,
          ),
          _b(
            'texture__noise',
            BibleBlockKind.text,
            'textField',
            'sensorNoise',
            'Sensor Noise Floor',
            colSpan: 6,
          ),
          _b(
            'texture__refs',
            BibleBlockKind.moodboardRefs,
            'moodboardRefs',
            'references',
            'Referencias visuales',
            rowSpan: 3,
          ),
        ],
      ),
      _page(
        id: 'location',
        groupId: 'spatial',
        label: 'Localización',
        sortOrder: 0,
        recipe: PageLayoutRecipeRegistry.locationHero,
        blocks: [
          _b(
            'location__narrative',
            BibleBlockKind.narrative,
            'narrativeIntent',
            'narrative',
            'Intención narrativa',
            rowSpan: 3,
          ),
          _b(
            'location__refs',
            BibleBlockKind.moodboardRefs,
            'moodboardRefs',
            'references',
            'Referencias visuales',
            rowSpan: 3,
          ),
        ],
      ),
      _page(
        id: 'camera_tests',
        groupId: 'spatial',
        label: 'Pruebas de cámara',
        sortOrder: 1,
        recipe: PageLayoutRecipeRegistry.cameraTests,
        blocks: [
          _b(
            'tests__narrative',
            BibleBlockKind.narrative,
            'narrativeIntent',
            'narrative',
            'Intención narrativa',
            rowSpan: 3,
          ),
          _b(
            'tests__refs',
            BibleBlockKind.moodboardRefs,
            'moodboardRefs',
            'references',
            'Referencias visuales',
            rowSpan: 3,
          ),
        ],
      ),
      _page(
        id: 'workflow',
        groupId: 'operational',
        label: 'Workflow',
        sortOrder: 0,
        recipe: PageLayoutRecipeRegistry.workflowPipeline,
        blocks: [
          _b(
            'workflow__narrative',
            BibleBlockKind.narrative,
            'narrativeIntent',
            'narrative',
            'Intención narrativa',
            rowSpan: 3,
          ),
          _b(
            'workflow__pipe',
            BibleBlockKind.text,
            'textField',
            'workflowSettings',
            'Pipeline de workflow',
            colSpan: 6,
          ),
          _b(
            'workflow__refs',
            BibleBlockKind.moodboardRefs,
            'moodboardRefs',
            'references',
            'Referencias visuales',
            rowSpan: 3,
          ),
        ],
      ),
      _page(
        id: 'moodboard',
        groupId: 'operational',
        label: 'Moodboard',
        sortOrder: 1,
        recipe: PageLayoutRecipeRegistry.moodboardMasonry,
        blocks: [
          _b(
            'moodboard__narrative',
            BibleBlockKind.narrative,
            'narrativeIntent',
            'narrative',
            'Intención narrativa',
            rowSpan: 3,
          ),
          _b(
            'moodboard__refs',
            BibleBlockKind.moodboardRefs,
            'moodboardRefs',
            'references',
            'Referencias visuales',
            rowSpan: 3,
          ),
        ],
      ),
    ];

    final doc = BibleDocument(
      projectId: 0,
      themeId: BibleThemeIds.irisStandard,
      themes: [theme],
      groups: groups,
      pages: pages,
      exportSettings: const {
        'idealFor': 'Producción cinematográfica / estándar IRIS',
        'previewStyle': BibleThemeIds.irisStandard,
      },
      updatedAt: DateTime.utc(2026, 1, 1),
    );

    return BibleTemplatePackage(
      id: id,
      name: 'IRIS Estándar',
      description:
          'Los 13 apartados de la Biblia clásica en motor V2, con look glass cinematic.',
      author: 'IRIS DP',
      version: 1,
      category: 'Estándar',
      document: doc,
      theme: theme,
      exportSettings: doc.exportSettings,
      createdAt: DateTime.utc(2026, 1, 1),
    );
  }

  static BiblePage _page({
    required String id,
    required String groupId,
    required String label,
    required int sortOrder,
    required String recipe,
    required List<BibleBlock> blocks,
  }) {
    return BiblePage(
      id: id,
      groupId: groupId,
      label: label,
      sortOrder: sortOrder,
      legacySectionId: id,
      layoutRecipeId: recipe,
      pageMode: BiblePageMode.recipe,
      blocks: blocks,
    );
  }

  static BibleBlock _b(
    String id,
    BibleBlockKind type,
    String subsectionKind,
    String fieldKey,
    String label, {
    int colSpan = 12,
    int rowSpan = 2,
  }) {
    return BibleBlock(
      id: id,
      type: type,
      layout: BibleBlockLayout(colSpan: colSpan, rowSpan: rowSpan),
      content: {
        ...BibleBlockContract.defaultContentForSubsection(subsectionKind),
        'label': label,
        'text': '',
        'fieldKey': fieldKey,
        'subsectionKind': subsectionKind,
        if (type == BibleBlockKind.moodboardRefs)
          'images': <Map<String, dynamic>>[],
        if (type == BibleBlockKind.chipSelect) ...{
          'chips': <String>[],
          'selected': <String>[],
        },
        if (type == BibleBlockKind.colorPalette)
          'colors': <Map<String, dynamic>>[],
        if (type == BibleBlockKind.telemetry)
          'metrics': [
            {'label': 'Kelvin', 'value': ''},
            {'label': 'Ratio', 'value': ''},
            {'label': 'IRE', 'value': ''},
          ],
      },
    );
  }
}
