import 'package:flutter_test/flutter_test.dart';
import 'package:iris_dp/core/utils/scene_format.dart';

void main() {
  test('formatSceneMetaLine usa slugline canónica', () {
    expect(
      formatSceneMetaLine(
        intExt: 'EXT',
        dayNight: 'NOCHE',
        location: 'PARADA DE BUS',
      ),
      'EXT. PARADA DE BUS - NOCHE',
    );
  });

  test('isAutoGeneratedSceneName detecta nombres derivados', () {
    expect(
      isAutoGeneratedSceneName(
        name: 'EXT. PARADA DE BUS - NOCHE',
        intExt: 'EXT',
        dayNight: 'NOCHE',
        location: 'PARADA DE BUS',
      ),
      isTrue,
    );
    expect(
      isAutoGeneratedSceneName(
        name: 'EXT NOCHE PARADA DE BUS',
        intExt: 'EXT',
        dayNight: 'NOCHE',
        location: 'PARADA DE BUS',
      ),
      isTrue,
    );
    expect(
      isAutoGeneratedSceneName(
        name: 'La persecución',
        intExt: 'EXT',
        dayNight: 'NOCHE',
        location: 'PARADA DE BUS',
      ),
      isFalse,
    );
  });

  test('locationFromCanonical extracts location from slugline', () {
    expect(
      locationFromCanonical('INT. COCINA DE MARÍA - DÍA'),
      'COCINA DE MARÍA',
    );
  });
}
