/// Formato consistente de metadatos de escena en toda la app.
String locationFromCanonical(String canonical) {
  final match =
      RegExp(r'^[A-Z/]+\.\s*(.+?)\s*-\s*.+$').firstMatch(canonical.trim());
  return match?.group(1)?.trim() ?? canonical.trim();
}

/// Línea slugline estándar: INT/EXT. LUGAR - MOMENTO
String formatSceneMetaLine({
  required String intExt,
  required String dayNight,
  required String location,
}) {
  final ext = intExt.trim();
  final loc = location.trim();
  final moment = dayNight.trim();
  final prefix = ext.endsWith('.') ? ext : '$ext.';
  return '$prefix $loc - $moment';
}

/// Nombre por defecto al persistir (misma forma que la slugline).
String formatSceneDefaultName({
  required String intExt,
  required String dayNight,
  required String location,
}) =>
    formatSceneMetaLine(intExt: intExt, dayNight: dayNight, location: location);

/// true si [name] es solo metadatos auto-generados, no un título propio.
bool isAutoGeneratedSceneName({
  required String? name,
  required String intExt,
  required String dayNight,
  required String location,
}) {
  if (name == null || name.trim().isEmpty) return true;
  final normalized = name.trim();
  final slugline =
      formatSceneMetaLine(intExt: intExt, dayNight: dayNight, location: location);
  final legacyDefault = _legacyDefaultSceneName(
    intExt: intExt,
    dayNight: dayNight,
    location: location,
  );
  bool matches(String a, String b) =>
      a.toUpperCase() == b.toUpperCase();
  return matches(normalized, slugline) || matches(normalized, legacyDefault);
}

String _legacyDefaultSceneName({
  required String intExt,
  required String dayNight,
  required String location,
}) =>
    '$intExt $dayNight $location';

String formatSceneTitle({
  required int number,
  required String intExt,
  required String dayNight,
  required String location,
}) =>
    '$number. ${formatSceneMetaLine(intExt: intExt, dayNight: dayNight, location: location)}';
